local me = peripheral.find("meBridge")

print("Only Items:")
local start = os.epoch("utc")
print(start)
me.listItems()
local stop = os.epoch("utc")
print(stop)
print("Result: "..((stop-start)/1000).."s")

print("All lists:")
local start = os.epoch("utc")
print(start)
local a = me.listItems()
local b = me.listFluid()
local c = me.listGas()
local stop = os.epoch("utc")
print(stop)
print("Result: "..((stop-start)/1000).."s")
